### ISSUE TITLE
Node version 

### ISSUE THREAD

**Issue by parseb** [monerium/sdk#30]
I have used the sdk and found two significant issues. Sorry for the fuzziness on the details. 

- requires node 18 and cloudflare pages supports up to 17
- importing and initializing the client server-side fails as it leads to undefined behavior (sveltekit). Not good enough of a javascripter to know why that happens but it does raise questions as to how am I supposed to keep bank secrets secure.

**Comment by einaralex** [comment]
Hey! Sorry for the late reply.

1. This package relies heavily on the built-in fetch introduced in v18. I've tried building it with v17 and the `NODE_OPTIONS=--experimental-fetch` flag, that seems to work ok, but it breaks the Jest tests. So there is a way around it, maybe with `yarn install --ignore-engines.`
Versions under 17 require a complete revamp of this package since it's not supported by the builder, Vite.
I'm the only maintainer of this package so I won't be adding node backward compatibility soon.

Fortunately, this package is not doing complex things; it's just encapsulating the Monerium API, and most functions are just making a direct request there. Authentication is the most complex part.

All of the logic behind this SDK can be found here:
https://github.com/monerium/sdk/blob/main/src/client.ts
[Docs authentication.](https://monerium.dev/docs/api)
[API Documentation - Auth](https://monerium.dev/api-docs#operation/auth)

2. Importing and initializing the client works fine with the server side on NextJs. I'll need some more details, maybe a code sample/sandbox to know what is going on here.

**Comment by parseb** [comment]
Fair point.
I reproduced the import error here:
https://github.com/parseb/monerium-import-error
(steps: initialized new app, `yarn add "@monerium/sdk"`, import in *.server.js file, yarn run dev)
Thanks. Feel free to close.

**Comment by einaralex** [comment]
Thank you so much for your time and effort in providing me with a test repo 🙏 highly appreciate it.
Svelte didn't want to recognize `*.es.js` files as es6 modules, there is a fix for this included in version [2.0.18](https://github.com/monerium/sdk/compare/v2.0.17...v2.0.18)

**Comment by einaralex** [comment]
Good news @parseb ! 

I just discovered that the `NODE_OPTIONS=--experimental-fetch` flag is supported back to Node v16.15.
The[ latest version](https://github.com/monerium/sdk/releases/tag/v2.2.1) of the SDK has supported node engine as [">= 16.15" ](https://github.com/monerium/sdk/commit/a80379b8849f78e541d9f4455cd12cd676e7751f)
